sudo: false
language: node_js
node_js:
  - "4.0"
  - "0.12"
  - "0.10"

before_install:
  - npm i -g npm
  - npm config set loglevel warn

script:
  - karma start karma.conf-testingbot.js

notifications:
  email: false

env:
  global:
  - secure: sfYzhIT4U/eCEuWxTOJ/2N2POwieViFYc1uxCLX42L+ugea6+/89KdHdTvjykfDJhOCPHwUR8iuXYCqrREPp1dGW5fb1bAGVJaHrk0f6dFtB7GFSoxEMTiaQml5dKrOZ97LqmbrSdJslgmx09nrgQJP0oRF/+PGtm8x7BeD8tAUjNDUT9PgMXuCPPuRxT30IT6pzmMfcZmFwvmjWi5vWtzD+ptCwyYlFjuBtGUtlSQsxCuUx+wAR0F1tv3KxaBryWadrwQuuuSvJ6E60bRIIto7CJbWDATGjWDiMULl0sEf1K1r5QfPyypnOfO0pteJ5qkt0RDG9uLhKtAt8vVyKCu95jZ76BT2anI3AsOw62i2znG7HUXorcWOpta7krGZAmj6wrUV06ryHubGMRvWTZ3rJ8W2oc3RKHNxBi3dis6qgm8F4PsZwJ+obSqQLAlTYReAQ2TK+qdfKnloD6LOGkDbdNLvsSaOw1Wd6DM6H8Re38/oFJ3xKx1yA2W2tYl4CnS2Ml/X2vK1S79sQpMZp/aRFaodoZ8X7SOKYuitPI2ysoXaOz66ko6B4CV7bUHk/ah4R097iT10QOs2ki+GcryU88iNtswbWLBiiGa1ca2S04BhuAAFJuacPz3olhvKwW8+SWbp5W1r4H7Jpzz3zLzBn/TujywvbHxysTLafiA0=
  - secure: p8eadSBRx0BFvHmtRuIrF865wMR+v5qwLOzuUBvLT4f4onYK0rRZ586ffh8qXPsr0g9iZBotlstod29EbjsInUaPAYxta5tAtEwfYJ6lbniMHYl+x0+S1bRpJgud94Bor8pHkAjiWxJstYKhQ/5BTVDgbIutrOF8mHOoy0LK5muevQprMj5ExuhSGgn/pV46QzFtIA/2O+KrWhBIxEMbcLIYS+w+1peBcYXydBwVlWqf/AAc23C0g87+7evyb4TGRNN9K8IAdKSxuwOsRXyqpmN/VSBIDTPTvhfUvGeKBOqJHLPw+72yuDn9VWHKVsmPw8wKWcQpqVfTgdc4fnSm1GzTKA5rnv85bv3U9LTVZguVPV6nrj3E35QaTEEHLTl/52HySrvLwP3s4gjcr+M6pNA2WOwctlZkQri7s++IVa0GdMAKxt4fIRcwhiqAK/DwY+tdqZbldSgi7ZwlCEJRhRcpOKjUuRumI/Ekmao/+XC7GgfSoVJxYR1c4M5swQiRUg3xVOlm5i/piDRsUjsmdRNyTpwq2ufY4dwZMfA+Z3qU1jgkg/EWPUnuZgwP+js/M0EWYDc7I3r/9i/PrT3hOLi1soDJRVHyMClTTkVQrFFJ0Sb7W8HTttFnfXQVwyWgl+nDsNjmqiqwtkr0WTJq6pikcCTuEsMtg7M3FG3p9Bk=